name: non-inclusive

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  woke:
    name: woke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: woke
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true
